// clientes/livros-angular2/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro('', 0, '', '' ,[]);
  autoresForm: string = '';
  editoras: Editora[] = [];

  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;
  private router: Router;
  constructor(
    servEditora: ControleEditoraService,
    servLivros: ControleLivrosService,
    router: Router
  ) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
    this.router = router;
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = async () => {
    this.livro.autores = this.autoresForm.split('\n').map(autor => autor.trim());
    await this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista')
    });

  };
}

<main class="container">
  <h1 class="mt-4 mb-4">Inclusão de Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="mb-3">
      <label htmlFor="titulo" class="form-label">Título:</label>
      <input type="text" class="form-control" id="titulo" [(ngModel)]="livro.titulo" name="titulo" required />
    </div>
    <div class="mb-3">
      <label htmlFor="resumo" class="form-label">Resumo:</label>
      <textarea class="form-control" id="resumo" [(ngModel)]="livro.resumo" name="resumo" required ></textarea>
    </div>
    <div class="mb-3">
      <label htmlFor="editora" class="form-label">Editora:</label>
      <select class="form-select" id="editora" [(ngModel)]="livro.codEditora" name="editora" required>
        <option *ngFor="let editora of editoras" [ngValue]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>
    <div class="mb-3">
      <label htmlFor="autores" class="form-label">Autores:</label>
      <textarea class="form-control" id="autores" [(ngModel)]="autoresForm" name="autoresForm" required></textarea>
    </div>

    <div class="mb-3">
      <button type="submit" class="btn btn-primary">Incluir Livro</button>
    </div>
  </form>
</main>

// clientes/livros-next/pages/LivroDados.tsx
import { controleEditora } from "@/classes/controle/ControleEditora";
import { ControleLivros } from "@/classes/controle/ControleLivros";
import { Menu } from "@/components/Menu";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import styles from '../styles/Home.module.css';

const LivroDados: NextPage = () => { 
  const router = useRouter();
  const controleLivros = new ControleLivros()

  const opcoes = controleEditora.getEditoras().map(editora => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(opcoes[0].value);

  const tratarCombo = (event: React.ChangeEvent<HTMLSelectElement>) => {
    const novoCodEditora = Number(event.target.value);
    setCodEditora(novoCodEditora);
  };

  const incluir = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const novoLivro = {
      codigo: "",
      titulo,
      resumo,
      codEditora,
      autores: autores.split('\n')
    };

    await controleLivros.incluir(novoLivro);
    router.push('/LivroLista');
  };
  
  
  return (
    <>
      <Head>
        <title>Página de Livros</title>
      </Head>
    
      <div className={styles.container} >

      <Menu paginaAtiva="LivroDados" />

      <main>
        <h1>Adicionar Livro</h1>
        <form onSubmit={incluir}>
        <div className="mb-3">
          <label htmlFor="titulo" className="form-label">Título:</label>
          <input type="text" className="form-control" id="titulo" value={titulo} onChange={(e) => setTitulo(e.target.value)} />
        </div>
        <div className="mb-3">
          <label htmlFor="resumo" className="form-label">Resumo:</label>
          <textarea className="form-control" id="resumo" value={resumo} onChange={(e) => setResumo(e.target.value)} />
        </div>
        <div className="mb-3">
          <label htmlFor="editora" className="form-label">Editora:</label>
          <select className="form-select" id="editora" value={codEditora} onChange={tratarCombo}>
            {opcoes.map((opcao) => (
              <option key={opcao.value} value={opcao.value}>
                {opcao.text}
              </option>
            ))}
          </select>
        </div>
        <div className="mb-3">
          <label htmlFor="autores" className="form-label">Autores:</label>
          <textarea className="form-control" id="autores" value={autores} onChange={(e) => setAutores(e.target.value)} />
        </div>
        
        <div className="mb-3">
          <button type="submit" className="btn btn-primary">Incluir Livro</button>
        </div>
      </form>
      </main>
      </div>
    </>
  )

}


export default LivroDados;
